defaults: &defaults
  options:
    identity_map_enabled: true

development:
  <<: *defaults
  sessions:
    default:
      hosts:
        - 127.0.0.1:27017
      database: anna_patio_development

test:
  <<: *defaults
  sessions:
    default:
      hosts:
        - 127.0.0.1:27017
      database: anna_patio_test

# set these environment variables on your prod server
production:
  <<: *defaults
  sessions:
    default:
      hosts:
        - 10.241.27.99:27017
      database: anna_patio